name: 'release-vir'
description: 'Automatically generate a release on GitHub for version tags.'
branding:
    icon: 'tag'
    color: 'blue'
inputs:
    include_npm_pack:
        description: 'If set to "true", `npm pack` will be run and its output will be included in the release assets. If applicable, ake sure you compile your TypeScript code before using this action.'
        default: 'false'
    token:
        description: 'Token used to access the repo with'
        default: ${{ github.token }}
outputs:
    release_url:
        description: 'The URL of the newly created release on GitHub.'
runs:
    using: 'node20'
    main: 'src/action-entry-point.js'
